### ISSUE TITLE
Remove words from dictionary

### ISSUE THREAD

**Issue by paperbenni** [overleaf/web#673]
## Steps to Reproduce

1.Add a word to the dictionary
2.Try to remove it from the dictionary
3.Doesn't work

## Expected Behaviour

There should be an option (other than mailing support) to remove incorrect entries from the dictionary.
## Context

I added an incorrect entry to the dictionary and because I don't want to think twice about it every time I add something, it's gonna happen again. I'm pretty sure other people have this problem too. I really like overleaf, but this one is honestly making me want to sacrifice the cloud-convenience for a working spell-checker.

**Comment by fishur** [comment]
Can we bump up this feature request/bug?

**Comment by rahav** [comment]
How do I remove a word that was added by mistake into Overleaf editor?

Working on Mac OS using Chrome.

**Comment by samuelgfeller** [comment]
I added a faulty word to the dictonary by mistake. How do I remove it?

**Comment by fishur** [comment]
> I added a faulty word to the dictionary by mistake. How do I remove it?

I did the same, there is not feature in overleaf to remove words from the dictionary at the moment. Though it seams lite there is a lot of interest for it (and it is a very reasonable feature to have) so will probably be implemented soon.

**Comment by paperbenni** [comment]
> I added a faulty word to the dictonary by mistake. How do I remove it?

Accept your fate to live with your past mistakes for all eternity.

**Comment by douira** [comment]
Had this happen to me too today, this would be really nice.

**Comment by sylqiu** [comment]
+1, would be really nice to have, otherwise the mistake may be harder to find.

**Comment by AndersJoerg** [comment]
+1

**Comment by schneider7** [comment]
Had this happen today. Would like to add to the list of people who would like this :)

**Comment by DorotheaKolossa** [comment]
same here - this would be a very helpful feature!

**Comment by jeffmak** [comment]
+1

**Comment by KSepetanc** [comment]
+1

**Comment by voges** [comment]
It would also be nice to be able to view/inspect the dictionary...

**Comment by spydx** [comment]
Is missing this feature in overleaf

**Comment by MichaelClerx** [comment]
Yes please!

**Comment by PyMarc2** [comment]
please.

**Comment by zachary-m** [comment]
+1

**Comment by oshears** [comment]
+1

**Comment by yuewuo** [comment]
+1

**Comment by raynalm** [comment]
+1

**Comment by anatoli-ulmer** [comment]
+1

**Comment by egeres** [comment]
+1

**Comment by jhalderm** [comment]
+1

**Comment by LucaKrummi** [comment]
I would be delighted if this feature is available.

**Comment by areejokaili** [comment]
+1

**Comment by zanoo** [comment]
Would definitely find this useful. +1

**Comment by boorac** [comment]
+1 no doubt about it

**Comment by danula** [comment]
+1

**Comment by rsha256** [comment]
This could easily be fixed by allowing users to view their dictionary as a `.csv` or the like.

**Comment by glavrentiadis** [comment]
+1

**Comment by OnlyFreeUsername** [comment]
Please bump this feature request/bug. It is a massive disruption of the dictionary feature rendering it almost useless. How is it possible that such an important issue is just ignored for more than a year?

**Comment by jsillerfarfan** [comment]
This is a clear bug. How come they have not fixed it in more than 2 years? Disgusting.

**Comment by OnlyFreeUsername** [comment]
I guess the issue fits better in this repository: https://github.com/overleaf/spelling/issues/79
Hope it gets addressed in the near future

**Comment by gh2k** [comment]
Thanks, @OnlyFreeUsername 

I wrote up a response in https://github.com/overleaf/spelling/issues/79#issuecomment-772390120 which I'm copying here:

The spelling API does actually contain an endpoint to remove words. There is no UI in Spelling, so I think as far as this repo is concerned there is no additional work to be done.

The biggest problem we have here is that we run an [in-process LRU cache](https://github.com/overleaf/spelling/blob/5ff31a24ccba0b8364dd46b8ba425f9ce60a08cb/app/js/MongoCache.js#L9) because, without it, the load on the database becomes impractically heavy.

The problem this causes on the Overleaf SaaS product in production is that we have at least 10 (often more) spelling services running to handle the demand. These each have their own cache, which can take a while to expire. What happens in this case when we provide a UI for editing the spelling dictionary, is that it can take a long time (~10 hours or so) for changes to appear. This causes an awful lot of confusion, and is very much sub-optimal.

We *are* aware of the problem and we have this on our roadmap to fix this year. tbh we've had a lot of technical debt to clean up since we merged ShareLaTeX and Overleaf - which is why we haven't been able to divert resources to this yet. We recognise that it's an important issue for our users, and also causes us a headache from a support perspective as people have to write to us to have their words removed manually.

I hope this helps clear this up -- I'm sorry that it's taken us so long to get onto it.

**Comment by douira** [comment]
If caching is an issue, one idea might be to just have a second list of deleted out-words that hides words from the spelling recommendations if it's in the list. This list could also be flushed when all deleted out-words it contains are out of the cache of in-words.

**Comment by OnlyFreeUsername** [comment]
Thank you for this information. Apparently I didn't pay enough attention to the overleaf/spelling API. The problem for me was that it seemed as if this issue was forgotten about since we didn't hear anything except +1 in this thread. btw, is there any public roadmap / trello board or something?

**Comment by gh2k** [comment]
Thanks @douira - we have some ideas in the pipeline for this, but architecturally it's not quite that simple.

> is there any public roadmap / trello board or something

Not yet. This is something that we are talking about internally, but while we've had so much tech debt to deal with I don't think it would make sense to publish it. I think this may change in the future.

I'd also note that for feature requests and issues with the Overleaf SaaS product, the support team at support@overleaf.com are very responsive. (And can remove dictionary words for you.)

**Comment by RoeeSinai** [comment]
> The spelling API does actually contain an endpoint to remove words. There is no UI in Spelling, so I think as far as this repo is concerned there is no additional work to be done.

How do I call this endpoint? I have an assignment to submit on Monday and I can't concentrate on writing the solutions because I accidentally entered a bad dictionary entry.

**Comment by gh2k** [comment]
> How do I call this endpoint? I have an assignment to submit on Monday and I can't concentrate on writing the solutions because I accidentally entered a bad dictionary entry.

Assuming that you are using overleaf.com, you can't call this externally. If you email support@overleaf.com they can clean this up for you. Please use this address rather than Github for technical support.

**Comment by RoeeSinai** [comment]
> > How do I call this endpoint? I have an assignment to submit on Monday and I can't concentrate on writing the solutions because I accidentally entered a bad dictionary entry.
> 
> Assuming that you are using overleaf.com, you can't call this externally. If you email [support@overleaf.com](mailto:support@overleaf.com) they can clean this up for you. Please use this address rather than Github for technical support.

I thought there was some URL I could enter or some JavaScript function I could call from the console to do this myself and this could be a temporary solution before you actually add a GUI option for this, but I guess I have to contact the support email. Thanks!

**Comment by Ran-n** [comment]
+1

**Comment by besendorf** [comment]
As there is no UI for this yet. Does someone know how to do this manually for a self hosted instance?

**Comment by schae211** [comment]
+1

**Comment by ahmadomira** [comment]
+1

**Comment by SebastianNechita** [comment]
+1

**Comment by PyLorentz** [comment]
+1

**Comment by Art-MC** [comment]
+1

**Comment by ozhanozen** [comment]
+1

**Comment by PaulEasterMonash** [comment]
+1

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
